# Generated by Django 5.1.4 on 2024-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.FileField(default=2000, upload_to='images/'),
            preserve_default=False,
        ),
    ]
