# Generated by Django 5.1.4 on 2024-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_facilities_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='bathroom',
            field=models.BooleanField(default=True),
        ),
    ]
