# Generated by Django 5.1.4 on 2024-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_facilities_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='adults',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='children',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.IntegerField(max_length=10),
        ),
    ]
