# Generated by Django 5.1.4 on 2024-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_adults_alter_room_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.IntegerField(),
        ),
    ]
