# Generated by Django 5.1.4 on 2024-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_adults_alter_room_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.CharField(max_length=20),
        ),
    ]
