# Generated by Django 5.1.4 on 2024-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_room_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
