# Generated by Django 5.1.4 on 2024-12-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_temprary_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temprary_Order',
            new_name='Temporary_Order',
        ),
    ]
