# Generated by Django 5.1.4 on 2024-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_temporary_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_order',
            name='adults',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='temporary_order',
            name='children',
            field=models.CharField(max_length=11),
        ),
    ]
